version: "3"
services:
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: simcomp@jku.at
      PGADMIN_DEFAULT_PASSWORD: simcomp
    networks:
      - local-net
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - local-net
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes/postgres/init:/docker-entrypoint-initdb.d:ro
      - ./volumes/postgres/data:/var/lib/postgresql/data
networks:
  local-net:
