version: "3"
services:
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: simcomp@jku.at
      PGADMIN_DEFAULT_PASSWORD: simcomp
    networks:
      - local-net
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - local-net
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes/postgres/init:/docker-entrypoint-initdb.d:ro
      - ./volumes/postgres/data:/var/lib/postgresql/data
  manager:
    image: jkuswesimcomp/manager:${ADAPTOR_MANAGER_VERSION}
    container_name: manager
    ports:
      - "${ADAPTOR_MANAGER_PORT}:8080"
    networks:
      - local-net
    environment:
      DATASOURCE_URL: ${ADAPTOR_MANAGER_DATASOURCE_URL}
      SERVICE_REGISTRY_ENDPOINT: ${SERVICE_REGISTRY_ENDPOINT}
      AXIS_CONVERTER_ENDPOINT: http://axis-converter:8080
    volumes:
      - ./volumes/manager/logs:/home/app/logs
    depends_on:
      - postgres
  registry:
    image: jkuswesimcomp/service-registry:${SERVICE_REGISTRY_VERSION}
    container_name: registry
    ports:
      - "${SERVICE_REGISTRY_PORT}:8080"
    networks:
      - local-net
    environment:
      DATASOURCE_URL: ${SERVICE_REGISTRY_DATASOURCE_URL}
    volumes:
      - ./volumes/registry/logs:/home/app/logs
    depends_on:
      - postgres
  demo-adaptor:
    image: jkuswesimcomp/demo-adaptor:${DEMO_ADAPTOR_VERSION}
    container_name: demo-adaptor
    ports:
      - "${DEMO_ADAPTOR_PORT}:8080"
    networks:
      - local-net
    environment:
      SERVICE_REGISTRY_ENDPOINT: ${SERVICE_REGISTRY_ENDPOINT}
      ADAPTOR_HOST: demo-adaptor
    depends_on:
      - registry
  simcomp-ui:
    image: jkuswesimcomp/simcomp-ui:${SIMCOMP_UI_VERSION}
    container_name: simcomp-ui
    ports:
      - "${SIMCOMP_UI_PORT}:3000"
  webots-adaptor:
    image: jkuswesimcomp/webots-adaptor:${WEBOTS_ADAPTOR_VERSION}
    container_name: webots-adaptor
    ports:
      - "${WEBOTS_ADAPTOR_PORT}:8080"
    networks:
      - local-net
    environment:
      SERVICE_REGISTRY_ENDPOINT: ${SERVICE_REGISTRY_ENDPOINT}
      ADAPTOR_HOST: webots-adaptor
    depends_on:
      - registry
  axis-converter:
    image: jkuswesimcomp/axis-converter:${AXIS_CONVERTER_VERSION}
    container_name: axis-converter
    ports:
      - "${AXIS_CONVERTER_PORT}:8080"
    networks:
      - local-net
networks:
  local-net:
