version: "3"
services:
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: simcomp@jku.at
      PGADMIN_DEFAULT_PASSWORD: simcomp
    networks:
      - local-net
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - local-net
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes/postgres/init:/docker-entrypoint-initdb.d:ro
      - ./volumes/postgres/data:/var/lib/postgresql/data
  registry:
    image: jkuswesimcomp/service-registry:${SERVICE_REGISTRY_VERSION}
    container_name: registry
    ports:
      - "${SERVICE_REGISTRY_PORT}:8080"
    networks:
      - local-net
    environment:
      DATASOURCE_URL: ${SERVICE_REGISTRY_DATASOURCE_URL}
    depends_on:
      - postgres
networks:
  local-net:
