version: "3"
services:
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: simcomp@jku.at
      PGADMIN_DEFAULT_PASSWORD: simcomp
    networks:
      - local-net
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - local-net
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes/postgres/init:/docker-entrypoint-initdb.d:ro
      - ./volumes/postgres/data:/var/lib/postgresql/data
  manager:
    image: jkuswesimcomp/manager:${ADAPTOR_MANAGER_VERSION}
    container_name: manager
    ports:
      - "${ADAPTOR_MANAGER_PORT}:8080"
    networks:
      - local-net
    environment:
      DATASOURCE_URL: ${ADAPTOR_MANAGER_DATASOURCE_URL}
      SERVICE_REGISTRY_ENDPOINT: ${SERVICE_REGISTRY_ENDPOINT}
      AXIS_CONVERTER_ENDPOINT: http://axis-converter:8080
      IS_INVERSE_KINEMATICS_ENABLED: ${IS_INVERSE_KINEMATICS_ENABLED}
      IS_DIRECT_KINEMATICS_ENABLED: ${IS_DIRECT_KINEMATICS_ENABLED}
    volumes:
      - ./volumes/manager/logs:/home/app/logs
    depends_on:
      - postgres
  registry:
    image: jkuswesimcomp/service-registry:${SERVICE_REGISTRY_VERSION}
    container_name: registry
    ports:
      - "${SERVICE_REGISTRY_PORT}:8080"
    networks:
      - local-net
    environment:
      DATASOURCE_URL: ${SERVICE_REGISTRY_DATASOURCE_URL}
    volumes:
      - ./volumes/registry/logs:/home/app/logs
    depends_on:
      - postgres
  axis-converter:
    image: jkuswesimcomp/axis-converter:${AXIS_CONVERTER_VERSION}
    container_name: axis-converter
    ports:
      - "${AXIS_CONVERTER_PORT}:8080"
    networks:
      - local-net
    volumes:
      - ./volumes/axis-converter/logs:/home/app/logs
networks:
  local-net:
