version: "3"
services:
  demo-adaptor:
    image: jkuswesimcomp/demo-adaptor:${DEMO_ADAPTOR_VERSION}
    container_name: demo-adaptor
    ports:
      - "${DEMO_ADAPTOR_PORT}:8080"
    networks:
      - local-net
    environment:
      SERVICE_REGISTRY_ENDPOINT: ${SERVICE_REGISTRY_ENDPOINT}
      ADAPTOR_HOST: ${HOST_IP}
      REGISTRATION_DELAY_MS: ${REGISTRATION_DELAY_MS}
    volumes:
      - ./volumes/demo-adaptor/logs:/home/app/logs
networks:
  local-net:
